### ISSUE TITLE
I cant do anything in admin

### ISSUE THREAD

**Issue by EliElite** [ZasticBradyn/blacket-hacks#11]
there is nothing to do in admin always says f*** off or just doesnt work

**Comment by Road-Block-coder** [comment]
That is because the blacket owner disabled admin for some time.

**Comment by Snowflake-Coder-H2o** [comment]
@Road-Block-coder Why?

**Comment by EliElite** [comment]
Oki thanks

**Comment by Greenlio** [comment]
admin's been disabled, you can't admin if you aren't admin

**Comment by ZasticBradyn** [comment]
there's server-sided checks to see if you are admin.

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn When he does the code and puts it to open-source will we be able to make our own version or something like this? So we can be admin? Or will that not be allowed.

**Comment by ZasticBradyn** [comment]
> @ZasticBradyn When he does the code and puts it to open-source will we be able to make our own version or something like this? So we can be admin? Or will that not be allowed.

yeah, you will be able to host it on your PC, and u can give yourself admin

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn Ok thanks for your help. I also invited you as ac contribuator on some of my github repos.
