### ISSUE TITLE
Stop (a polite request)

### ISSUE THREAD

**Issue by Greenlio** [ZasticBradyn/blacket-hacks#13]
you're bad. stop making them. no good.

**Comment by Snowflake-Coder-H2o** [comment]
@Greenlio LMAO can you code?

**Comment by Snowflake-Coder-H2o** [comment]
@Greenlio No you can't dont come at people for not being good at coding.

**Comment by Snowflake-Coder-H2o** [comment]
@Greenlio This dude has coded alot of things for me.

**Comment by Greenlio** [comment]
yes, i can, and much better than you can.
aren't you using a blooket hack?
please shut your mouth. anything you continue is simply stupid.
zastix didn't find the method and is using it for popularity. in fact, it's borderline if not just copied code.

i'm gonna go at people for being bad at coding when they use someone else's work and attempt to make popularity or even monetary gain from something like this.

stop being weird.

**Comment by ZasticBradyn** [comment]
This isn't even for blooket, and I've stopped using gliz's method for a while now, and my goal was never to gain popularity or gain anything in general, thanks for being polite about your request.

**Comment by Snowflake-Coder-H2o** [comment]
I suck at coding. I know that. Im not using blooket hacks. I use blAcket hacks.

**Comment by ZasticBradyn** [comment]
> yes, i can, and much better than you can. aren't you using a blooket hack? please shut your mouth. anything you continue is simply stupid. zastix didn't find the method and is using it for popularity. in fact, it's borderline if not just copied code.
> 
> i'm gonna go at people for being bad at coding when they use someone else's work and attempt to make popularity or even monetary gain from something like this.
> 
> stop being weird.

also I'm not sure what you mean by "I didn't find the method", it's just editing react values, it's not rocket science.

**Comment by Greenlio** [comment]
didn't you admit in larptide discord that the only way you figured out the method was by reading code gliz left in by accident and reading git logs

**Comment by Snowflake-Coder-H2o** [comment]
@Greenlio What method ou guys talking about?

**Comment by Snowflake-Coder-H2o** [comment]
@Greenlio What method ou guys talking about?

**Comment by Greenlio** [comment]
no :)

**Comment by Snowflake-Coder-H2o** [comment]
@Greenlio wha method you talking bout?

**Comment by ZasticBradyn** [comment]
> @Greenlio wha method you talking bout?

```js
let hack = Object.values(document.querySelector('.arts__body___3acI_-camelCase'))[1].children[1]._owner
```

**Comment by ZasticBradyn** [comment]
> didn't you admit in larptide discord that the only way you figured out the method was by reading code gliz left in by accident and reading git logs

yeah, but that doesn't take away from my statement at all.
