### ISSUE TITLE
These hacks are awesome!

### ISSUE THREAD

**Issue by FallGuysFan1234** [ZasticBradyn/blacket-hacks#14]
:D

**Comment by FallGuysFan1234** [comment]
> @FallGuysFan1234 He always does great on these hacks he always out does himself every time.

Yup!

**Comment by Juzxery** [comment]
It sucks how do u hack with this trash

**Comment by ZasticBradyn** [comment]
> It sucks how do u hack with this trash

read the instructions, and how about you go do something meaningful instead of going on GitHub hating on people's work that they took time out of their day to create for you.

**Comment by Snowflake-Coder-H2o** [comment]
@Juzxery Get good then talk about other peoples hacks!

-Snow
