### ISSUE TITLE
Issue in Console

### ISSUE THREAD

**Issue by nokal416** [ZasticBradyn/blacket-hacks#16]
When I open console it says this:
Hold Up!
​ If someone told you to copy/paste something here you have an 11/10 chance you're being scammed.
​ Pasting anything in here could give attackers access to your Blacket account.
What should I do? Does this mean I shouldn't use the hacks?

**Comment by ZasticBradyn** [comment]
No, while pasting scripts can give attackers access to your account, these scripts are open-source so you can see that they don't steal your account.
