### ISSUE TITLE
boxes and blooks.

### ISSUE THREAD

**Issue by ivmu** [ZasticBradyn/blacket-hacks#18]
bro why did you guys remove the old boxes like the OG box and add token box and things like that old blacket was better in my op but tell him to add them back cuz they were awesome.

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu He wont add them back sorry for the inconvuience.

**Comment by ivmu** [comment]
i dont understand why?

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu Becuase they were too op

**Comment by ivmu** [comment]
blacket now sucks bro one cuz the blooks arent as cool as they used to be. two ADMIN doesnt even work just logs me out. this is legit bad bro.

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu THEN DONT USE IT STOP WASTEING TIME AND COMMETNING

**Comment by ivmu** [comment]
bro shut up not my fault i just found out about blacket.

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu Then how you know about the old boxes?

**Comment by ivmu** [comment]
saw a video

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu Then you dont know if u like it or not so stop being so repeditive.

**Comment by ivmu** [comment]
im repetitive huh says the person who keeps commenting on every issue/post I make when I dont need YOUR help ok buddy. Second of all your not giving any good information just comments or statements when I did not need them tbh your being inquisitive. So stop. Feel free to tell me yourself @ZasticBradyn

**Comment by ivmu** [comment]
everything that you say is unproductive.

**Comment by ZasticBradyn** [comment]
> bro why did you guys remove the old boxes like the OG box and add token box and things like that old blacket was better in my op but tell him to add them back cuz they were awesome.

i dont own blacket, i would ask XOTIC (the owner of blacket), but he probably wont add them back.

Also please stop being rude its not helping anything.

**Comment by Snowflake-Coder-H2o** [comment]
> > bro why did you guys remove the old boxes like the OG box and add token box and things like that old blacket was better in my op but tell him to add them back cuz they were awesome.
> 
> i dont own blacket, i would ask XOTIC (the owner of blacket), but he probably wont add them back.
> 
> Also please stop being rude its not helping anything.

Thank you!
