### ISSUE TITLE
don't use add token it'll ban you

### ISSUE THREAD

**Issue by Rookiehecker** [ZasticBradyn/blacket-hacks#34]
It literally removes your account, how brutal!  But thanks for my IQ I figured out to use alt account for hacking LOL

**Comment by Footinsack** [comment]
That is hilarious
For most games I play, I have 2 accounts.

**Comment by ZasticBradyn** [comment]
AddTokens.js is a hack that can easily get you banned, There was a warning message in the script. I'm sorry, but there isn't anything i can do.
