### ISSUE TITLE
Blacket.

### ISSUE THREAD

**Issue by ivmu** [ZasticBradyn/blacket-hacks#38]
So idk whats going on with blacket but whenever I put in beta.blacket.org it just takes me to the copyright thing that ben wrote on discord. So zastic if you could help me on this thats much appreciated a lot! But for other people having this problem just go to xotic.org

Regards,
               Ivmu

**Comment by ZasticBradyn** [comment]
> So idk whats going on with blacket but whenever I put in beta.blacket.org it just takes me to the copyright thing that ben wrote on discord. So zastic if you could help me on this thats much appreciated a lot! But for other people having this problem just go to xotic.org
> 
> Regards, Ivmu

Yeah ben said some more stuff to xotic now its hosted at http://xotic.org/
