### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [ZasticBradyn/blacket-hacks#39]
@ZasticBradyn Are you able to make a hack that dupes your blooks and coins then sells them? or something along the lines of that?

**Comment by ZasticBradyn** [comment]
> @ZasticBradyn Are you able to make a hack that dupes your blooks and coins then sells them? or something along the lines of that?

All blook data is stored in the database, so we can't dupe them.

**Comment by ZasticBradyn** [comment]
> @ZasticBradyn Also Can you give me the multitool? Im your friend?

It's not done yet, but you can join my server and ill give it to you when it releases'
https://discord.gg/xxBtqPHSjW

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn  O ok. Also Can u look at discussions tab I asked u something

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn Wait for free? youll give me the tool?

**Comment by ZasticBradyn** [comment]
> @ZasticBradyn Wait you will give me the multitool for free? is it the full version or a demo?

full

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn Ok
