### ISSUE TITLE
Blacket

### ISSUE THREAD

**Issue by Snowflake-Coder-H2o** [ZasticBradyn/blacket-hacks#4]
Why did you change the Blacket URL to acccess it?

**Comment by Snowflake-Coder-H2o** [comment]
@ZasticBradyn The same open boxes isnt working. 


-Snow

**Comment by ZasticBradyn** [comment]
> Why did you change the Blacket URL to acccess it?

he bought a new domain

**Comment by ZasticBradyn** [comment]
> @ZasticBradyn The same open boxes isnt working.
> 
> -Snow

he added a delay so it takes 4ever
