### ISSUE TITLE
whats xotics discord name.

### ISSUE THREAD

**Issue by ivmu** [ZasticBradyn/blacket-hacks#40]
I need it so i can ask him to add back the boxes also @ZasticBradyn can we trade on blacket please?!? cuz one i need tokens 2 I wanna trade you something.??

**Comment by ivmu** [comment]
my blacket name is 365Dolphinz @ZasticBradyn So we can trade.

**Comment by ZasticBradyn** [comment]
XOTIC#0001 is his discord

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu He said no. NO means NO.

**Comment by ZasticBradyn** [comment]
> cmon zastix please

sorry im really not looking to trade right now

**Comment by ivmu** [comment]
@Snowflake-Coder-H2o BRO STOP COMMENTING ON MY POSTS YOUR GETTING ANNOYING NOBODY ASKED YOU! Think I dont know that?? (btw you wanna trade snow or no)

**Comment by ivmu** [comment]
bro I am. Hes been doing this for the past week now. I get it hes your friend but he needs to stop fr.

**Comment by Snowflake-Coder-H2o** [comment]
Look When someone says no that means no. Don't keep on asking. Like I've said before, Stop being repetitive. I come into convos when my friend is getting annoyed. And No I don't wanna trade because u prob have nothing I want. Also, you commenting on a post many times is productive? No, I didn't think so. I've only been doing it for a couple of days.

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu It wasent a whole week though. It been off and on. But not constantly for a whole week. I have done everything I need to do.

**Comment by ivmu** [comment]
still you could be a lot brighter ya know. No need to go off on me.

**Comment by ivmu** [comment]
for certain words its called emphasizing your point.

**Comment by Snowflake-Coder-H2o** [comment]
LMAO for certain words? You used all caps for EVERYTHING

**Comment by ivmu** [comment]
in the first message I sent to you sure yeah but that wasnt a point that was just straight dis belief.

**Comment by ZasticBradyn** [comment]
im deleting this issue now
