### ISSUE TITLE
Not an issue but...

### ISSUE THREAD

**Issue by ivmu** [ZasticBradyn/blacket-hacks#41]
I want to trade with you @ZasticBradyn on blacket cuz I saw how many tokens you have and I really need some atm and I wanna trade some blooks and stuff if your down?

**Comment by ivmu** [comment]
Come on bro.

**Comment by ivmu** [comment]
youve actually been really getting on my nerves all week man you need to stop commenting on my posts okay.

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu Then dont comment here?

**Comment by Snowflake-Coder-H2o** [comment]
Im commenting on everyones' post not just urs calm down

**Comment by Snowflake-Coder-H2o** [comment]
How am I overprotective? its called careing for friends?

**Comment by ivmu** [comment]
thats all fine and dandy but however he did not say he was annoyed and you need to realize things were not out of control and messages come in late so.

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu Fair enough.

**Comment by Snowflake-Coder-H2o** [comment]
Also

**Comment by ivmu** [comment]
lol tbh really nothing but tokens and a couple chromas but what do you have?

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu What chromas and how many tokens.

**Comment by ivmu** [comment]
i think like 5k but i can trade my other tokens on to this account and i have 2 green astros

**Comment by ivmu** [comment]
Like @Snowflake-Coder-H2o  we can be friends if you want? Sorry about the rude introduction earlier (no i dont have rage problems if thats what your thinking)

**Comment by Snowflake-Coder-H2o** [comment]
Black, Brown, Cyan, Green, Lime, Orange, Pink, Purple, and Red  astro thats the only good stuff

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu Its all good and thats fine we can be friends

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu I will gladly trade for the otkens

**Comment by Snowflake-Coder-H2o** [comment]
I need the tokens thats it

**Comment by Snowflake-Coder-H2o** [comment]
But Im packing up to go home rn

**Comment by ivmu** [comment]
So what you trading for them.

**Comment by Snowflake-Coder-H2o** [comment]
So can we trade in like 30 minutes?

**Comment by Snowflake-Coder-H2o** [comment]
The red and orange atro and the santa can we do te 5k tokens?

**Comment by ivmu** [comment]
sure ill give 5k

**Comment by Snowflake-Coder-H2o** [comment]
ok we can trade in 30 minutes I need to go home rn

**Comment by ivmu** [comment]
so ill contact you back at 3:49 whats your user btw?

**Comment by ivmu** [comment]
Mine is 365Dolphinz

**Comment by ivmu** [comment]
can you take out the santa and add red instead and ill add a blook along with the 5.8k tokens?

**Comment by Snowflake-Coder-H2o** [comment]
@ivmu The pink astro isnt for trade. Also My user is HelloHello

**Comment by ivmu** [comment]
okay what about the lime? and are you ready to traade?

**Comment by ivmu** [comment]
I sent you a request.

**Comment by Snowflake-Coder-H2o** [comment]
Sure I can take out the santa and put in the lime one. Im ready

**Comment by Snowflake-Coder-H2o** [comment]
Send again please

**Comment by ivmu** [comment]
okay accept the trade.

**Comment by Snowflake-Coder-H2o** [comment]
Sent request

**Comment by ivmu** [comment]
okay got it

**Comment by Snowflake-Coder-H2o** [comment]
Ok so 5.8k tokens?

**Comment by ivmu** [comment]
how will we do this since you can only put 1 blook in?

**Comment by Snowflake-Coder-H2o** [comment]
You give me the coins and I send another trade request

**Comment by Snowflake-Coder-H2o** [comment]
I give u the rest

**Comment by ivmu** [comment]
ok i only have 5620 my bad

**Comment by Snowflake-Coder-H2o** [comment]
U said 5.8k?

**Comment by ivmu** [comment]
my bad i read it wrong eek

**Comment by Snowflake-Coder-H2o** [comment]
Its ok

**Comment by Snowflake-Coder-H2o** [comment]
Accept

**Comment by ivmu** [comment]
send another

**Comment by Snowflake-Coder-H2o** [comment]
Just sent another trade

**Comment by Snowflake-Coder-H2o** [comment]
Accept

**Comment by Snowflake-Coder-H2o** [comment]
Now the orange one I sent another btw

**Comment by Snowflake-Coder-H2o** [comment]
Accept

**Comment by Snowflake-Coder-H2o** [comment]
Thank you for the coins

**Comment by ivmu** [comment]
i can give more tokens

**Comment by Snowflake-Coder-H2o** [comment]
How many more?

**Comment by ivmu** [comment]
what will that get me?

**Comment by Snowflake-Coder-H2o** [comment]
one sec let me see what I have

**Comment by ivmu** [comment]
i gtg but ill be back in 30 minutes or less let me know what you can give me and ill give the tokens.

**Comment by Snowflake-Coder-H2o** [comment]
ok

**Comment by ivmu** [comment]
btw i want the black or purple astro if thats okay gtg bye!

**Comment by ivmu** [comment]
is that fine?

**Comment by Snowflake-Coder-H2o** [comment]
Sure I can give the black one

**Comment by ivmu** [comment]
Hey are you still here?

**Comment by ivmu** [comment]
I just got back!

**Comment by ivmu** [comment]
@Snowflake-Coder-H2o
