### ISSUE TITLE
bro whats happening with blacket and xotic.org??

### ISSUE THREAD

**Issue by ivmu** [ZasticBradyn/blacket-hacks#42]
it says 404 not found on xotic.org WHATS GOING ON IS BLACKET BEING BANNED?

**Comment by FallGuysFan1234** [comment]
Yo xotic.org is pretty funny XD But yea, beta.blacket.org stopped working I wonder why D:

**Comment by 123345666777777777777777777777777** [comment]
They are updating.Back up in 2-4 weeks

**Comment by Snowflake-Coder-H2o** [comment]
@123345666777777777777777777777777 Currently we are redesigning

**Comment by ZasticBradyn** [comment]
^
